agent_portal/urls.py
from django.views.generic import TemplateView, RedirectView
from django.conf.urls import patterns, url
from django.conf import settings

urlpatterns = patterns('agent_portal.views',
    url(r'^$', TemplateView.as_view(template_name='agent_portal/home_v2.html'), name="home"),
    url(r'^register/$', 'register_view', name="agent_register"),
    url(r'^reset/password/', 'reset_password_view', name='reset_password'),
    url(r'^login/$', 'login_step_one_view', name="agent_login"),
    url(r'^login_confirmation/$', 'login_step_two_view', name="login_step_two"),
    url(r'^dashboard/$', 'dashboard_view', name="dashboard"),
    url(r'^request_fund/$', 'request_fund_view', name="request_fund"),
    url(r'^transactions/(?P<type_>\w+)/$', 'transaction_view', name='transactions'),
    url(r'^transfer/$', 'transfer_view', name='transfer'),
    url(r'^otp/$', 'otp_view', name='otp_view'),
    url(r'^transfer/(?P<iden>\w+)/$', 'transfer_invoice_view', name='transfer_invoice_view'),
    url(r'^logout/$', 'logout_view', name='logout'),
    url(r'^rates/$', 'rate_view', name='rate'),
    url(r'^find-agents/$', 'find_agents_view', name='agents_finder'),
    url(r'^favicon\.ico$', RedirectView.as_view(url=settings.STATIC_URL + 'agent_portal/img/favicon.ico')),

)

novapay/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'novapay.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^collection/', include('collection.urls')),
    url(r'^rsp/', include('rsp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^agent/', include('agent_portal.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'settlement/', include('settlement.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'sanctions_app/', include('sanctions_list.urls')),
    url(r'^', include('agent_portal.urls')),



)

rsp/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('rsp.views',
    url(r'^api/exchange/(?P<currency>\w+)/$', 'exchange_rate_view'),
    url(r'^api/deposit/(?P<currency>\w+)/(?P<amount>\d+)/$', 'calculate_deposit_view'),
    url(r'^api/limit/(?P<currency>\w+)/(?P<dimen>\w+)/$', 'currency_limit_view'),
    url(r'^api/holders/name/(?P<_code>\w+)/(?P<_account>\w+)/$', 'bank_holders_name_view'),
    url(r'^api/transfer/$', 'transfer_funds_view'),

)

agent_portal/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.db.models import Sum
from django.core.exceptions import ObjectDoesNotExist
from rsp.errors import InvalidAmountException

from datetime import datetime


# Create your models here.
id_type = (
        ('ID', 'IDENTITY CARD'),
        ('IP', 'INTERNATIONAL PASSPORT'),
        ('DL', 'DRIVERS LICENSE'),
    )



class Currency(models.Model):
    """
        Currency supported on our platform for money transfer
    """
    name = models.CharField(max_length=20, unique=True)
    exchange_rate = models.DecimalField(max_digits=65, decimal_places=2)
    minimum_per_transfer = models.DecimalField(max_digits=65, decimal_places=2)
    maximum_per_transfer = models.DecimalField(max_digits=65, decimal_places=2)
    symbol = models.CharField(max_length=2)
    abbreviation = models.CharField(max_length=10)
    selling_margin = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=65)

    def get_selling_price_exchange_rate(self):
        return self.exchange_rate + self.selling_margin

    def __unicode__(self):
        return self.name





class Country(models.Model):
    """
        Countries supported with currency foreign key
    """
    name = models.CharField(max_length=100, unique=True)
    abbreviation = models.CharField(max_length=10)
    currency = models.ForeignKey(Currency)


    def __unicode__(self):
        return self.name


class Mto(models.Model):
    """
    Mto/Aggregator information provided during partnership
    """
    name = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=100)
    agent_commission = models.DecimalField(max_digits=65, decimal_places=2, default=Decimal('0'))
    platform_commission = models.DecimalField(max_digits=65, decimal_places=2, default=Decimal('100'))
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']


    def __unicode__(self):
        return self.name



class Rate(models.Model):
    rate = models.DecimalField(max_digits=64, decimal_places=2)
    currency = models.ForeignKey(Currency)
    mto = models.ForeignKey(Mto)
    selling_margin = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=65)

    @classmethod
    def get_exchange_rate(cls, agent):
        try:
            rate = cls.objects.get(currency=agent.country.currency, mto=agent.mto)
            exchange_rate = rate.rate
        except ObjectDoesNotExist:
            exchange_rate = agent.country.currency.exchange_rate

        return exchange_rate

class Schedule(models.Model):
    commission_types = (
        ('percentage', 'Percentage'),
        ('fixed', 'Fixed')
    )
    greater_than_equal_to = models.DecimalField(max_digits=64, decimal_places=2)
    less_than_equal_to = models.DecimalField(max_digits=64, decimal_places=2)
    commission_type = models.CharField(max_length=20, choices=commission_types)
    commission = models.DecimalField(max_digits=64, decimal_places=2)
    mto = models.ForeignKey(Mto)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return str(self.greater_than_equal_to) + str(self.less_than_equal_to)


class Agent(models.Model):
    """
        Registered agents information
    """

    user = models.OneToOneField(User)
    country = models.ForeignKey(Country)
    city = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    phone1 = models.CharField(max_length=20)
    phone2 = models.CharField(max_length=20, blank=True)
    social_security_number = models.CharField("Social Security Number | NI Number ", max_length=50)
    mto = models.ForeignKey(Mto)
    identification_type = models.CharField(max_length=20, choices=id_type)
    identification_number = models.CharField(max_length=50)
    business_name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    date_of_birth = models.CharField(max_length=10)
    account_balance = models.DecimalField(max_digits=65, decimal_places=2, default=Decimal('0.0'))
    super_agent = models.ForeignKey('self', null=True, blank=True,)
    is_super_agent = models.BooleanField(default=False)
    credit = models.DecimalField(max_digits=65, decimal_places=2, default=Decimal('0.0'))



    def __unicode__(self):
        return self.user.username

    def is_secret_answer_correct(self, question=None, answer=None):
        try:
            Secret.objects.get(agent=self, question=question, answer=answer)
            return True
        except Exception:
            return False

    def latest_transfers(self, size=5):
        query_set = Transfer.objects.filter(agent=self)[:size]
        return query_set

    def latest_funds(self, size=5):
        query_set = Fund.objects.filter(requested_by=self)[:size]
        return query_set

class Payment(models.Model):
    amount = models.DecimalField(max_digits=65, decimal_places=2)
    collected_on = models.DateTimeField(auto_now_add=True)
    agent = models.ForeignKey(Agent)

    class Meta:
        ordering = ['-collected_on']




secret_questions = ('Where were you born?', 'Who is your favourite celebrity?',
                    'What is the name of your favourite childhood friend?', 'In what city or town was your first job?')
class Secret(models.Model):
    """
    Secret question and md5 hashed answers for registered agents
    """
    agent = models.ForeignKey(Agent)
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)

    def __unicode__(self):
        return self.question




class Fund(models.Model):
    """
        Requested funds by agents.
    """
    fund_types = (
        ('bank deposit', 'Bank Deposit'),
        ('mto/aggregator deposit', 'MTO/AGGREGATOR DEPOSIT'),
        ('credit', 'CREDIT'),
    )
    fund_status = (('r', 'rejected'), ('p', 'pending'), ('f', 'funded'))
    requested_by = models.ForeignKey(Agent)
    funded_by = models.ForeignKey(User, null=True)
    amount = models.DecimalField(max_digits=65, decimal_places=2)
    type = models.CharField(max_length=100, choices=fund_types)
    currency = models.CharField(max_length=100)
    requested_on = models.DateTimeField(auto_now_add=True)
    funded_on = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=fund_status)

    class Meta:
        ordering = ['-requested_on']

class ErrorLog(models.Model):
    status = models.CharField(max_length=10)
    error_code = models.CharField(max_length=10)

def calculate_commission(amount, agent):
    mto_schedules = Schedule.objects.filter(mto=agent.mto)

    for schedule in mto_schedules:
        if amount >= schedule.greater_than_equal_to and amount <= schedule.less_than_equal_to:
            if schedule.commission_type == 'percentage':
                return schedule.commission * amount
            else:
                return schedule.commission

    raise InvalidAmountException('Amount does not have schedule')

class Transfer(models.Model):
    """
        Transfer made by registered agents.
    """
    transfer_status = (
        ('s', 'success'),
        ('f', 'failed')
    )
    supported_banks = (
        ('044', 'ACCESS BANK'),
        ('023', 'CITI Bank'),
        ('063', 'DIAMOND BANK'),
        ('401', 'ASO SAVINGS'),
        ('050', 'ECOBANK'),
        ('084', 'ENTERPRISE BANK'),
        ('040', 'EQUITORIAL TRUST BANK LIMITED'),
        ('070', 'FIDELITY BANK'),
        ('011', 'FIRST BANK OF NIGERIA'),
        ('214', 'FIRST CITY MONUMENT BANK'),
        ('085', 'FIRST INLAND BANK'),
        ('058', 'GUARANTY TRUST BANK'),
        ('030', 'HERITAGE BANK'),
        ('069', 'INTERCONTINENTAL BANK'),
        ('082', 'KEYSTONE BANK'),
        ('014', 'MAINSTREET BANK'),
        ('056', 'OCEANIC BANK'),
        ('076', 'SKYE BANK'),
        ('221', 'STANBIC IBTC BANK'),
        ('068', 'STANDARD CHARTERED BANK NIGERIA LTD'),
        ('232', 'STERLING BANK'),
        ('032', 'UNION BANK'),
        ('033', 'UNITED BANK FOR AFRICA'),
        ('215', 'UNITY BANK'),
        ('035', 'WEMA BANK'),
        ('057', 'ZENITH BANK'),
    )

    settlement_status_choices = (
        ('pending', 'Pending'),
        ('settled', 'settled')
    )
    agent = models.ForeignKey(Agent)
    amount_in_currency = models.DecimalField(max_digits=65, decimal_places=2)
    amount_in_local_currency = models.DecimalField(max_digits=65, decimal_places=2)
    fees_collected = models.DecimalField(max_digits=65, decimal_places=2)
    currency = models.CharField(max_length=100)
    exchange_rate = models.DecimalField(max_digits=65, decimal_places=2)
    narration = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    otp = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=transfer_status)
    senders_name = models.CharField(max_length=100, verbose_name='Senders Fullname')
    senders_id_type = models.CharField(max_length=20, choices=id_type)
    senders_id_number = models.CharField(max_length=50)
    senders_mobile = models.CharField(max_length=20)
    senders_address = models.CharField(max_length=50)
    senders_email = models.CharField(max_length=100, blank=True)
    beneficiary_bank_full_name = models.CharField(max_length=50)
    beneficiary_bank_number = models.CharField(max_length=15)
    beneficiary_mobile_number = models.CharField(max_length=20)
    beneficiary_bank_name = models.CharField(max_length=50, choices=supported_banks)
    platform_fees = models.DecimalField(max_digits=65, decimal_places=2, null=True, blank=True, default=Decimal('0'))
    amount_expected = models.DecimalField(max_digits=65, decimal_places=2, null=True, blank=True, default=Decimal('0'))
    agent_fees = models.DecimalField(max_digits=65, decimal_places=2, default=Decimal('0'), null=True, blank=True)

agent_portal/forms.py
from django import forms
from django.contrib.auth.models import User




from .models import secret_questions, Agent, Fund, Transfer, Mto, Schedule, Country, Currency, Rate

import random

class ResetPasswordForm(forms.Form):
    password1 = forms.CharField(min_length=8, max_length=40, widget=forms.PasswordInput, label="Password")
    password2 = forms.CharField(min_length=8, max_length=40, widget=forms.PasswordInput, label="Confirm password")

    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    pass

class UserForm(forms.ModelForm):

    error_messages = {
        'duplicate_username': "A user with that username already exists.",
        'password_mismatch': "The two password fields didn't match.",
    }

    username = forms.CharField(max_length=20, label="Username", help_text='')
    password1 = forms.CharField(min_length=8, max_length=20, widget=forms.PasswordInput, label="Password")
    password2 = forms.CharField(min_length=8, max_length=20, widget=forms.PasswordInput, label="Password confirmation", help_text="Enter the same password as above")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        # exclude = ('is_staff', 'is_active', 'date_joined', 'password', 'last_login')

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    pass


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country

class RateForm(forms.ModelForm):
    class Meta:
        model = Rate

class AgentForm(forms.ModelForm):
    super_agent = forms.ModelChoiceField(queryset=Agent.objects.exclude(is_super_agent=False), required=False)
    class Meta:
        model = Agent
        fields = ('country', 'city', 'address', 'phone1', 'social_security_number', 'mto',
                  'identification_type', 'identification_number', 'business_name', 'position', 'date_of_birth','super_agent',)
    pass

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule

class CurrencyForm(forms.ModelForm):
    class Meta:
        model = Currency

class SecretForm(forms.Form):
    question_1 = forms.CharField(max_length=100, label=secret_questions[0])
    question_2 = forms.CharField(max_length=100, label=secret_questions[1])
    question_3 = forms.CharField(max_length=100, label=secret_questions[2])
    question_4 = forms.CharField(max_length=100, label=secret_questions[3])

    pass

class SettlementLoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)

class MtoForm(forms.ModelForm):
    class Meta:
        model = Mto

class SecretLoginForm(forms.Form):
    question = forms.CharField(max_length=100, label=secret_questions[random.randrange(0, 3)])

class FundForm(forms.ModelForm):
    class Meta:
        model = Fund
        fields = ('type', 'amount')
    pass


class TransferForm(forms.ModelForm):
    class Meta:
        model = Transfer
        fields = ('amount_in_currency', 'narration', 'senders_name',
                  'senders_id_type', 'senders_id_number', 'senders_mobile', 'senders_address', 'senders_email',
                  'beneficiary_bank_name', 'beneficiary_bank_number', 'beneficiary_bank_full_name',
                  'beneficiary_mobile_number')

class OtpForm(forms.Form):
    otp = forms.CharField(max_length=100, label='Transfer otp')

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='Username')
    password = forms.CharField(widget=forms.PasswordInput)

templates/agent_portal/add-fund.html
{% extends 'agent_portal/base-2.html' %}
{% load staticfiles %}

{% block middle_pane %}
    {{ block.super }}



     <div class="col-md-12" id="activities-block">

            <div>
              <h4>Request Fund</h4>
              <hr>


              <form class="form-horizontal" action="/request_fund/" method="POST">
                  {% csrf_token %}
                <div class="form-group">
                  <label for="inputEmail3" class="col-md-2 control-label">Type</label>
                  <div class="col-md-10">
                    <select name="{{ form.type.html_name }}" class="form-control" required>

                        {% for value, text in form.type.field.choices %}
                      <option value="{{ value }}">{{ text }}</option>
                      {% endfor %}
                    </select>
                      <small>{{ form.type.errors }}</small>
                  </div>
                </div>

                <div class="form-group">
                  <label for="inputEmail3" class="col-md-2 control-label">{{ form.amount.label }}({{ agent.country.currency.symbol }})</label>
                  <div class="col-md-10">
                    <input type="number" name="{{ form.amount.html_name }}" class="form-control" required>
                      <small>{{ form.amount.errors }}</small>
                  </div>
                </div>

                <div class="form-group">
                  <label for="inputEmail3" class="col-md-2 control-label"></label>
                  <div class="col-md-10 ">
                    <input type="submit" value="Request fund" class="form-control btn btn-success">

                  </div>
                </div>
              </form>
            </div>
          </div>
{% endblock %}

templates/agent_portal/base-1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <title>NovaPay</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'agent_portal/css/style.css' %}">
      {% block head %}

      {% endblock %}
  </head>
  <body>
    {% block nav %}
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="top-navigation">
      <div class="container">
        {% include 'agent_portal/includes/brand.html' %}

        {% include 'agent_portal/includes/nav-out.html' %}
      </div>

    </nav>
    {% endblock %}


    {% block content %}

    {% endblock %}

    {% block footer %}
        {% include 'agent_portal/includes/footer.html' %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
   	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <style>
            .errorlist{
                color:red;
            }
        </style>
    {% block body %}

    {% endblock %}
  </body>
</html>

templates/agent_portal/dashboard.html
{% extends 'agent_portal/base-2.html' %}

        {% block middle_pane %}
            {{ block.super }}

            {% if message %}
            <div class="col-md-12 alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
            {% endif %}





            {% if error %}
            <div class="col-md-12 alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert alert-warning" aria-hidden="true">&times;</button>
                    {{ error }}
                </div>
            {% endif %}

            {% include 'agent_portal/includes/balance-block.html' %}



            <div class="col-md-12" id="activities-block">
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active"><a href="#transfers" data-toggle="tab">Transfers</a></li>
                    <li><a href="#funds" data-toggle="tab">Funds</a></li>
                </ul>



                <div class="tab-content">

              <div class="tab-pane active" id="transfers">

                {% if transfers %}
                <table class="table table-striped">
                  <tr class="warning">
                    <td><b>Amount</b></td>
                    <td><b>Beneficiary</b></td>
                    <td><b>Bank</b></td>
                    <td><b>Date</b></td>
                  </tr>

                    {% for transfer in transfers %}
                  <tr>
                   <td> {{ transfer.amount_in_currency | floatformat:-2 }}{{ agent.country.currency.abbreviation }}</td>
                   <td>{{ transfer.beneficiary_bank_full_name }}</td>
                   <td>{{ transfer.get_beneficiary_bank_name_display }}</td>
                   <td>{{ transfer.time | date:"D d M Y" }}</td>
                  </tr>
                    {% endfor %}
                  <tr>


                </table>
                  {% else %}
                  <br>
                  <p>No transfer has been done.</p>
                  {% endif %}

              </div>
              <div class="tab-pane" id="funds">

                  {% if funds %}
                <table class="table table-striped">
                  <tr class="info">
                    <td><b>Amount(USD)</b></td>
                    <td><b>Status</b></td>
                    <td><b>Date</b></td>
                  </tr>

                  {% for fund in funds %}
                  <tr>
                   <td>{{ fund.amount | floatformat:-2 }}{{ agent.country.currency.abbreviation }}</td>
                   <td>{{ fund.get_status_display }}</td>
                   <td>{{ fund.requested_on | date:"D d M Y" }}</td>
                  </tr>
                    {% endfor %}

                  <tr>

                </table>
                  {% else %}
                  <br>
                  <p>No fund has been requested yet.</p>
                  {% endif %}

              </div>
            </div>
          </div>
        {% endblock %}

templates/agent_portal/transfer-invoice.html
{% extends 'agent_portal/base-2.html' %}
        {% load staticfiles %}
{% block middle_pane %}
    {{ block.super }}


    <div class="col-md-12" id="activities-block">

            <div>
              <h4>Transfer ID: {{ transfer.id }} <small class="pull-right">Date: {{ transfer.time | date:"D d M Y"}}</small></h4>
              <hr>

              <form class="form-horizontal" id="transfer-form">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h5>Sender's Details</h5>
                  </div>

                  <div class="panel-body">
                    <div class="col-md-12">
                      <label>{{ transfer.senders_name }}</label>
                    </div>



                    <div class="col-md-6">
                       <label>{{ transfer.get_senders_id_type_display }}</label>
                    </div>

                    <div class="col-md-6">
                        <label>{{ transfer.senders_id_number }}</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{ transfer.senders_email }}</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{ transfer.senders_mobile }}</label>
                    </div>

                    <div class="col-md-6">
                     <label>{{ transfer.senders_address }}</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{ agent.country.name }}</label>
                    </div>


                  </div>


                </div>


                <div class="panel panel-danger">
                  <div class="panel-heading">
                    <h5>Beneficiary's Details</h5>
                  </div>

                  <div class="panel-body">
                    <div class="col-md-12">
                      <label>{{ transfer.beneficiary_bank_full_name }}</label>
                    </div>


                    <div class="col-md-6">
                      <label>{{ transfer.beneficiary_bank_number }}</label>
                    </div>

                    <div class="col-md-6">
                     <label>{{ transfer.get_beneficiary_bank_name_display }}</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{ transfer.beneficiary_mobile_number }}</label>
                    </div>



                    <div class="col-md-6">
                      <label>{{ transfer.narration }}</label>
                    </div>


                  </div>


                </div>


                <div class="panel panel-success">
                  <div class="panel-heading">
                    <h5>Tranfer Details</h5>
                  </div>

                  <div class="panel-body">

                    <div class="col-md-6">
                      <label>Amount</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{agent.country.currency.symbol }} {{ transfer.amount_in_currency| floatformat:-2 }} {{ agent.country.currency.abbreviation }}</label>
                    </div>

                     <div class="col-md-6">
                      <label>Amount in Naira</label>
                    </div>

                    <div class="col-md-6">
                      <label>{{ transfer.amount_in_local_currency | floatformat:-2 }}NGN</label>
                    </div>




                  </div>


                </div>

                <input type="submit" class="btn btn-success btn-lg" value="Process Transfer">
              </form>
            </div>
          </div>
{% endblock %}

templates/agent_portal/transfers.html
{% extends 'agent_portal/base-2.html' %}
        {% load staticfiles %}

        {% block middle_pane %}
    {{ block.super }}


      <div class="col-md-12" id="activities-block">
            <ul class="col-md-12 list-unstyled" id="transaction-history">
              <li class="active-transaction-tab"><a href="/transactions/transfers">All transfers</a></li>
              <li class=""><a href="/transactions/funds">All Funds</a></li>
            </ul>
            <div>
              <!--<form class="form-inline">-->
                <!--<div class="form-group">-->
                  <!--<input type="text" class="form-control" placeholder="reference no">-->
                <!--</div>-->
                <!--<div class="form-group">-->
                  <!--<input type="submit" name="find" class="btn" value="find">-->
                <!--</div>-->
              <!--</form>-->
              <br>

              {% if transactions %}
              <table class="table table-striped">
                <tr>
                  <td><b>Reference n<u>o</u></b></td>
                  <td><b>Beneficiary</b></td>
                  <td><b>Amount({{ agent.country.currency.symbol }})</b></td>
                  <td><b>Amount (Naira)</b></td>
                  <td><b>Status</b></td>
                  <td><b>Action</b></td>
                </tr>

                {% for transaction in transactions %}
                <tr>
                  <td><b>{{ transaction.id }}</b></td>

                  <td>{{ transaction.get_beneficiary_bank_name_display }}</td>
                  <td>{{ transaction.amount_in_currency| floatformat:-2 }}</td>
                  <td>{{ transaction.amount_in_local_currency| floatformat:-2 }}</td>
                  <td>{{ transaction.get_status_display }}</td>
                  <td><a href="/transfer/{{ transaction.id }}/">view</a></td>
                </tr>
                  {% endfor %}



              </table>
                {% else %}

                    <p style="margin-top:10px;">No transfers performed yet.</p>

                {% endif %}


              {% if transaction.paginator.has_other_pages %}
              <ul class="pagination">
                  {% if transaction.paginator.has_previous %}
                <li><a href="?page={{ transaction.paginator.previous_page_number }}">&laquo;</a></li>
                  {% endif %}
                {% if paginaor.has_next %}
                <li><a href="?page={{ transaction.paginator.next_page_number }}">&raquo;</a></li>
                {% endif %}
              </ul>
              {% endif %}

            </div>
          </div>
{% endblock %}