novapay/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'novapay.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^collection/', include('collection.urls')),
    url(r'^rsp/', include('rsp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^agent/', include('agent_portal.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'settlement/', include('settlement.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'sanctions_app/', include('sanctions_list.urls')),
    url(r'^', include('agent_portal.urls')),



)

rsp/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('rsp.views',
    url(r'^api/exchange/(?P<currency>\w+)/$', 'exchange_rate_view'),
    url(r'^api/deposit/(?P<currency>\w+)/(?P<amount>\d+)/$', 'calculate_deposit_view'),
    url(r'^api/limit/(?P<currency>\w+)/(?P<dimen>\w+)/$', 'currency_limit_view'),
    url(r'^api/holders/name/(?P<_code>\w+)/(?P<_account>\w+)/$', 'bank_holders_name_view'),
    url(r'^api/transfer/$', 'transfer_funds_view'),

)

settlement/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('settlement.views',
    url(r'dashboard/$', 'dashboard_view', name='settlement_dashboard'),
    url(r'transfers/$', 'transfers_view', name='settlement_transfers'),
    url(r'transfer/$', 'transfer_view', name='settlement_transfer'),
    url(r'agents/$', 'agents_view', name='settlement_agents'),
    url(r'agent/$', 'agent_view', name='settlement_agent'),
    url(r'funds/$', 'funds_view', name='settlement_funds'),
    url(r'fund_action/$', 'accept_reject_funds', name='settlement_fund_action'),
    url(r'payments/$', 'payments_view', name='settlement_payments'),
    url(r'add_payment/$', 'add_payment', name='settlement_add_payment'),
    url(r'mtos/$', 'mtos_view', name='settlement_mtos'),
    url(r'mto/$', 'mto_view', name='settlement_mto'),
    url(r'countries/$', 'country_view', name='settlement_country'),
    url(r'rates/$', 'rates_view', name='settlement_rates'),
    url(r'currencies/$', 'currencies_view', name="settlement_currencies"),
    url(r'rate/edit/$', 'edit_rate', name="settlement_edit_rate"),
    url(r'currency/edit/$', 'edit_currency', name="settlement_edit_currency"),
    url(r'^', 'login_view', name='settlement_login'),

)

rsp/models.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist

from helpers import build_signatures


from errors import AmountAboveMaximumException, AmountBelowMinimumException, OperationException

from errorcodes import ErrorMessages

class Mto(models.Model):
    dev_mode = (
        ('1', 'testing'),
        ('2', 'live'),
        ('3', 'default'),
    )
    vendor_id = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True)
    ip_address = models.CharField(max_length=20)
    token = models.CharField(max_length=200)
    dev = models.CharField(max_length=10, choices=dev_mode)

    def __unicode__(self):
        return self.name

    @classmethod
    def is_sig_correct(cls, vendor, mtcn, signature):
        try:
            mto = cls.objects.get(vendor_id=vendor)



            original_signature = build_signatures(vendor, mto.token, mtcn)

            if signature == original_signature:
                return True
        except ObjectDoesNotExist:
            return False
        pass

    @classmethod
    def is_mto_ip_correct(cls, vendor, ip):
        try:
            Mto.objects.get(vendor_id=vendor, ip_address=ip)
            return True
        except ObjectDoesNotExist:
            return False
        pass

class Currency(models.Model):
    name = models.CharField(max_length=50)
    exchange_rate = models.DecimalField(max_digits=65, decimal_places=2)
    minimum = models.DecimalField(max_digits=65, decimal_places=2, default=0.00)
    maximum = models.DecimalField(max_digits=65, decimal_places=2, default=0.00)
    # created_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


    @classmethod
    def not_below_minimum_and_not_above_maximum(cls, currency, amount_in_float):
        try:
            cur = cls.objects.get(name=currency)

            if cur.minimum > amount_in_float:
                raise AmountBelowMinimumException(ErrorMessages.amount_below_minimum)

            if cur.maximum < amount_in_float:
                raise AmountAboveMaximumException(ErrorMessages.amount_above_maximum)
        except cls.DoesNotExist:
            raise OperationException(ErrorMessages.currency_not_supported)
            pass


class Transfer(models.Model):
    supported_banks = (
        ('044', 'ACCESS BANK'),
        ('023', 'CITI Bank'),
        ('063', 'DIAMOND BANK'),
        ('401', 'ASO SAVINGS'),
        ('050', 'ECOBANK'),
        ('084', 'ENTERPRISE BANK'),
        ('040', 'EQUITORIAL TRUST BANK LIMITED'),
        ('070', 'FIDELITY BANK'),
        ('011', 'FIRST BANK OF NIGERIA'),
        ('214', 'FIRST CITY MONUMENT BANK'),
        ('085', 'FIRST INLAND BANK'),
        ('058', 'GUARANTY TRUST BANK'),
        ('030', 'HERITAGE BANK'),
        ('069', 'INTERCONTINENTAL BANK'),
        ('082', 'KEYSTONE BANK'),
        ('014', 'MAINSTREET BANK'),
        ('056', 'OCEANIC BANK'),
        ('076', 'SKYE BANK'),
        ('221', 'STANBIC IBTC BANK'),
        ('068', 'STANDARD CHARTERED BANK NIGERIA LTD'),
        ('232', 'STERLING BANK'),
        ('032', 'UNION BANK'),
        ('033', 'UNITED BANK FOR AFRICA'),
        ('215', 'UNITY BANK'),
        ('035', 'WEMA BANK'),
        ('057', 'ZENITH BANK'),
    )

    identification_types = (
        ('IP', 'International Passport'),
        ('DL', 'Drivers License'),
    )
    transaction_status = (('1', 'Successful'), ('0', 'Failed'))

    mto = models.ForeignKey(Mto)
    mtcn = models.CharField(max_length=100, editable=False)
    beneficiary_bank = models.CharField(max_length=10, choices=supported_banks, editable=False)
    beneficiary_bank_account_number = models.CharField(max_length=20, editable=False)
    beneficiary_bank_account_name = models.CharField(max_length=100, editable=False)
    narration = models.CharField(max_length=100)
    senders_fullname = models.CharField(max_length=50, editable=False)
    senders_id_type = models.CharField(max_length=50, choices=identification_types, editable=False)
    senders_id_number = models.CharField(max_length=50, editable=False)
    senders_country = models.CharField(max_length=50, editable=False)
    senders_state = models.CharField(max_length=50, editable=False)
    senders_mobile = models.CharField(max_length=50, editable=False)
    amount = models.DecimalField(max_digits=65, decimal_places=2, editable=False)
    currency = models.CharField(max_length=50, editable=False)
    exchange_rate = models.DecimalField(max_digits=65, decimal_places=2, editable=False)
    amount_in_naira = models.DecimalField(max_digits=65, decimal_places=2, editable=False)
    amount_in_naira_after_fees = models.DecimalField(max_digits=65, decimal_places=2, editable=False)
    fees = models.DecimalField(max_digits=65, decimal_places=2, default=0.00, editable=False)
    status = models.CharField(max_length=10, choices=transaction_status, editable=False)
    time = models.DateTimeField(auto_now_add=True)


    def __unicode__(self):
        return self.mtcn

    @classmethod
    def mtcn_already_used(cls, _mtcn):
        try:
            mtcn_ = cls.objects.get(mtcn=_mtcn)
            return True
        except ObjectDoesNotExist:
            return False


    @classmethod
    def add_transfer_to_db(cls, **kwargs):
        new_transfer = cls()

        for key, value in kwargs.items():
            if key == 'mto':
                new_transfer.__dict__[key+'_id'] = value.id
            else:
                new_transfer.__dict__[key] = value
            # print key, '==' ,type(value)



        if cls.mtcn_already_used(new_transfer.mtcn):
            raise OperationException(ErrorMessages.mtcn_already_used)
        new_transfer.save()
        return new_transfer.mtcn


class Alert(models.Model):
    error_types = (
        ('001', 'NIBSS'),
        ('002', 'APP')
    )
    type = models.CharField(max_length=5, choices=error_types)
    reason = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)

    @classmethod
    def add_alert(cls, **kwargs):
        alert = cls()

        for key, value in kwargs.items():
            alert.__dict__[key] = value

        alert.save()
        return alert.id

settlement/models.py
from django.db import models

# Create your models here.

templates/settlement/agent_detail.html
{% extends 'settlement/base.html' %}
        {% load staticfiles %}
        {% load humanize %}

        {% block header %}

        {% endblock %}

        {% block wrapper %}

            {% include 'settlement/includes/left-side.html' %}
            <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Agents Transfer
                <small>All</small>
            </h1>



        </section>

        <!-- Main content -->
        <section class="content">

            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <br>
                        <p><strong>{{ agent.user.first_name }} {{ agent.user.last_name }}</strong></p>
                        <p><strong>{{ agent.country }}</strong></p>
                        <p><strong>{{ agent.mto }}</strong></p>
                        <p><strong>{{ agent.account_balance|intcomma }}{{ agent.country.currency.abbreviation }}</strong></p>
                        <p>-{{agent.credit|intcomma}}{{ agent.country.currency.abbreviation }}</p>
                    </div>
                    <div class="col-md-4">
                        <img src="{% static 'agent_portal/img/user-profile.png' %}" width="" height="">
                    </div>
                </div>
                <form action="" method="GET">
                    <label>From: <input type="date" name="from" value="{{date_from}}" class="form-control"></label>
                    <label>To: <input type="date" name="to" value="{{date_to}}" class="form-control"></label>
                    <input type="hidden" name="key" value="{{agent.pk}}">
                    <input type="submit" class="btn" value="Filter">

                </form>
                <table class="table table-striped">
                    <tr class="table table-condensed">
                        <td></td>
                        <td><strong>Date</strong></td>
                        <td><strong>Amount</strong></td>
                        <td><strong>Amount in Naira</strong></td>
                        <td><strong>Exchange Rate</strong></td>
                        <td><strong>platform fees</strong></td>
                        <td><strong>Amount expected</strong></td>
                        <td><strong>Settlement status</strong></td>
                    </tr>
                    {% for transfer in transfers %}
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>{{ transfer.time|date }}</td>
                        <td>{{ transfer.amount_in_currency}}{{ agent.country.currency.abbreviation }}</td>
                        <td>NGN{{ transfer.amount_in_local_currency|intcomma }}</td>
                        <td>NGN{{ transfer.exchange_rate|intcomma }}</td>
                        <td>{{ transfer.platform_fees|intcomma }}{{ agent.country.currency.abbreviation }}</td>
                        <td>{{ transfer.amount_expected|intcomma }}{{ agent.country.currency.abbreviation }}</td>
                        <td>{{ transfer.get_settlement_status_display }}</td>
                    </tr>
                    {% endfor %}

                </table>
                <p><label>Total transfers: NGN {{ total_amount_transferred_in_naira|intcomma }}, {{agent.country.currency.abbreviation }}{{ total_amount_transferred|intcomma}}</label>

                    <label>No of Transactions: {{ total_number_of_transactions }}</label>
                    <label>Total platform fees: {{ total_platform_fees }}</label>
                    <label>Total Agent fees: {{ total_agent_fees }}</label>
                    <label>Total fees: {{ total_fees }}</label>
                    <label>Total Amount expected: {{ total_amount_expected }}</label>
                </p>
                <ul class="pagination">
                    {% if transfers.has_previous %}
                    <li><a href="?key={{agent.pk}}&page={{ transfers.previous_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">&laquo;Previous</a></li>
                    {% endif %}

                    {% if transfers.has_next %}
                    <li><a href="?key={{agent.pk}}&page={{ transfers.next_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">Next&raquo;</a></li>
                    {% endif %}
                </ul>

                <hr>
                <h4>Add Payment</h4>
                <form action="/settlement/add_payment/" method="GET" >
                    <label>Amount: <input type="text" name="amount"></label>
                    <input type="hidden" name="agent_key" value="{{ agent.pk }}">
                    <input type="submit" value="Add Payment">
                </form>

            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->


        {% endblock %}

templates/settlement/agents.html
{% extends 'settlement/base.html'%}
        {% load humanize %}
        {% block header %}
             {% include 'settlement/includes/header.html' %}
        {% endblock %}

        {% block wrapper %}
            {% include 'settlement/includes/left-side.html'%}

        <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Transfers
                <small>All</small>
            </h1>



        </section>

        <!-- Main content -->
        <section class="content">

            <div class="col-md-12">

                <table class="table table-striped">
                    <tr>
                        <td><b>Username</b></td>
                        <td><b>Balance</b></td>
                        <td><b>Country</b></td>
                        <td><b>Mto</b></td>
                        <td><b>is Super Agent</b></td>
                        <td><b>Super Agent is</b></td>
                        <td><b>Status</b></td>
                    </tr>
                    {% for agent in agents %}
                    <tr>
                        <td><a href="/settlement/agent/?key={{agent.pk}}">{{ agent.user.username }}</a></td>
                        <td>{{ agent.account_balance }}{{ agent.country.currency.abbreviation }}</td>
                        <td>{{ agent.country.abbreviation }}</td>
                        <td>{{ agent.mto.name }}</td>
                        {% if agent.is_super_agent %}
                        <td> Yes </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td>{{ agent.super_agent.user.username }}</td>
                        {% if agent.user.is_active %}
                        <td>Active</td>
                        {% else %}
                        <td>In active</td>
                        {% endif %}

                    </tr>
                    {% endfor %}
                </table>

                <ul class="pagination">
                    {% if transfers.has_previous %}
                    <li><a href="?page={{ transfers.previous_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">&laquo;Previous</a></li>
                    {% endif %}

                    {% if transfers.has_next %}
                    <li><a href="?page={{ transfers.next_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">Next&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->

        {% endblock %}

templates/settlement/dashboard.html
{% extends 'settlement/base.html' %}

        {% block header %}
            {% include 'settlement/includes/header.html' %}

        {% endblock %}

        {% block wrapper %}
            {% include 'settlement/includes/left-side.html'%}

            <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <!--<small>Dashboard</small>-->
            </h1>

        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-6">
                    <!-- small box -->
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3>
                                {{ total_agents }}
                            </h3>
                            <p>
                                Total Agents
                            </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person"></i>
                        </div>
                        <a href="#" class="small-box-footer">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>

                <div class="col-md-6">
                    <!-- small box -->
                    <div class="small-box bg-green">
                        <div class="inner">
                            <h3>
                                NGN {{ account_balance }}
                            </h3>
                            <p>
                                Account Balance
                            </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-speedometer"></i>
                        </div>
                        <a href="#" class="small-box-footer">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div><!-- ./col -->

                <div class="col-md-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                        <div class="inner">
                            <h3>
                                NGN {{ total_transfers_today }}
                            </h3>
                            <p>
                                Total Transfer Today
                            </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pound"></i>
                        </div>
                        <a href="#" class="small-box-footer">

                        </a>
                    </div>
                </div><!-- ./col -->

                <div class="col-md-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                        <div class="inner">
                            {% for currency in fx %}
                            <h3>
                               {{ currency.abbreviation | upper }} 1 - NGN {{ currency.exchange_rate }}
                            </h3>
                            {% endfor %}

                            <p>
                                FX Rates
                            </p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div><!-- ./col -->

                <div class="col-md-6">
                    <!-- small box -->
                  <div class="box">
                      <div class="box-header">
                          <h3 class="box-title">Recent Transfers</h3>
                      </div>

                      <div class="box-body">
                          <table class="table">
                              <tr>
                                  <td><b>Agent</b></td>
                                  <td><b>Amount($)</b></td>
                                  <td><b>Amount(#)</b></td>
                                  <td><b>Time</b></td>
                              </tr>
                              {% for transfer in recent_transfers %}
                              <tr>
                                  <td><b>{{ transfer.agent.user.username }}</b></td>
                                  <td><b>{{ transfer.agent.country.currency.abbreviation | upper }}{{ transfer.amount_in_currency }}</b></td>
                                  <td><b>{{ transfer.amount_in_local_currency }}</b></td>
                                  <td><b>{{ transfer.time | date}}</b></td>
                              </tr>
                              {% endfor %}


                          </table>
                      </div>
                  </div>
                </div><!-- ./col -->



                <div class="col-md-6">
                    <!-- small box -->
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Recent Funds</h3>
                        </div>

                        <div class="box-body">
                            <table class="table table-striped">
                                <tr>
                                    <td><b>Agent</b></td>
                                    <td><b>Amount($)</b></td>
                                    <td><b>Status</b></td>

                                </tr>


                                {% for fund in recent_funds %}
                                <tr>
                                    <td><b>{{ fund.requested_by.user.username }}</b></td>
                                    <td><b>{{ fund.requested_by.country.currency.abbreviation | upper }}{{ fund.amount}}</b></td>
                                    <td><b>{{ fund.get_status_display }}</b></td>

                                </tr>
                                {% endfor %}




                            </table>
                        </div>
                    </div>
                </div><!-- ./col -->
            </div>


        </section><!-- /.content -->
    </aside><!-- /.right-side -->

        {% endblock %}

templates/settlement/funds.html
{% extends 'settlement/base.html' %}
        {% load humanize %}
        {% load staticfiles %}


        {% block header %}
            {% include 'settlement/includes/header.html' %}
        {% endblock %}

        {% block wrapper %}
            {% include 'settlement/includes/left-side.html' %}
        <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Funds
                <small>All</small>
            </h1>



        </section>

        <!-- Main content -->
        <section class="content">

            <div class="col-md-12">
                <form action="" method="GET">
                    <label>From: <input type="date" name="from" value="{{date_from}}" class="form-control"></label>
                    <label>To: <input type="date" name="to" value="{{date_to}}" class="form-control"></label>
                    <label>
                        <select name="status">
                            <option value="">all</option>
                            <option value="y">Pending</option>
                        </select>
                    </label>
                    <input type="submit" class="btn" value="Filter">
                </form>
                <table class="table table-striped">
                    <tr>
                        <td><b>Agent</b></td>
                        <td><b>Amount</b></td>
                        <td><b>Type</b></td>
                        <td><b>Requested on</b></td>
                        <td><b>Status</b></td>
                        <td><b>Action</b></td>

                    </tr>
                    {% for fund in funds %}
                    <tr>
                        <td>{{ fund.requested_by.user.username }}</td>
                        <td>{{ fund.amount|intcomma }}{{ fund.requested_by.country.currency.abbreviation }}</td>
                        <td>{{ fund.get_type_display }}</td>
                        <td>{{ fund.requested_on|date}}</td>
                        <td>{{ fund.get_status_display|title }}</td>
                        {% if fund.status == 'p' %}
                        <td>
                            <a href="/settlement/fund_action/?key={{fund.pk}}&action=a" class="btn btn-success">Accept</a>
                            <a href="/settlement/fund_action/?key={{fund.pk}}&action=r" class="btn btn-danger">Reject</a>
                        </td>
                        {% else %}
                        <td>{{ fund.get_status_display }}</td>
                        {% endif %}
                    </tr>

                    {% endfor%}

                </table>

                <ul class="pagination">
                    {% if funds.has_previous %}
                    <li><a href="?page={{ funds.previous_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">&laquo;Previous</a></li>
                    {% endif %}

                    {% if funds.has_next %}
                    <li><a href="?page={{ funds.next_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">Next&raquo;</a></li>
                    {% endif %}
                </ul>

                <hr>



            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->
        {% endblock %}

templates/settlement/transfers.html
{% extends 'settlement/base.html'%}
        {% load humanize %}
        {% block header %}
             {% include 'settlement/includes/header.html' %}
        {% endblock %}

        {% block wrapper %}
            {% include 'settlement/includes/left-side.html'%}

        <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Transfers
                <small>All</small>
            </h1>



        </section>

        <!-- Main content -->
        <section class="content">

            <div class="col-md-12">
                <form action="" method="GET">
                    <label>From: <input type="date" name="from" value="{{date_from}}" class="form-control"></label>
                    <label>To: <input type="date" name="to" value="{{date_to}}" class="form-control"></label>
                    <input type="submit" class="btn" value="Filter">
                </form>
                <table class="table table-striped">
                    <tr>
                        <td><b>Agent</b></td>
                        <td><b>Amount()</b></td>
                        <td><b>Amount(NGN)</b></td>
                        <td><b>Platform fees</b></td>
                        <td><b>Wema fee (NGN)</b></td>
                        <td><b>Agent fees</b></td>
                        <td><b>Time</b></td>
                        <td><b>Exchange Rate(NGN)</b></td>
                        <td><b>Settlement status</b></td>
                        <td><b>Status</b></td>
                        <td><b>Action</b></td>
                    </tr>
                    {% for transfer in transfers %}
                    <tr>
                        <td>{{ transfer.agent.user.username }}</td>
                        <td>{{ transfer.amount_in_currency}}{{ transfer.agent.country.currency.abbreviation }}</td>
                        <td>{{ transfer.amount_in_local_currency|intcomma }}</td>
                        <td>{{ transfer.platform_fees }}</td>
                        <td>{{ transfer.wema_fee }}</td>
                        <td>{{ transfer.agent_fees }}</td>
                        <td>{{ transfer.time|date }}</td>
                        <td>{{ transfer.exchange_rate }}</td>
                        <td>{{ transfer.get_settlement_status_display }}</td>
                        <td>
                           {{ transfer.get_status_display }}
                        </td>
                        <td><a href="/settlement/transfer/?key={{transfer.pk}}">view</a></td>
                    </tr>
                    {% endfor %}
                </table>

                <ul class="pagination">
                    {% if transfers.has_previous %}
                    <li><a href="?page={{ transfers.previous_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">&laquo;Previous</a></li>
                    {% endif %}

                    {% if transfers.has_next %}
                    <li><a href="?page={{ transfers.next_page_number }}{% if date_from %}&from={{ date_from }}{%endif%}{% if date_to %}&to={{ date_to }}{% endif %}">Next&raquo;</a></li>
                    {% endif %}
                </ul>

                <hr>

                <h4>Aggregate</h4>
                <table class="table table-condensed">
                    <tr>
                        <td>Total Amount Transfered</td>
                        <td>NGN {{ transfers_sum_in_naira|intcomma}}</td>
                    </tr>

                    <tr>
                        <td>Total Platform fees</td>
                        <td>{{ total_platform_fees|intcomma }} GBP</td>
                    </tr>

                    <tr>
                        <td>Total fees collected by Wema</td>
                        <td>{{ total_wema_fees|intcomma }} in {{ total_transactions }} payments</td>
                    </tr>

                    <tr>
                        <td>Total fess to Agent</td>
                        <td>{{ total_fees_collected_by_agent|intcomma }}</td>
                    </tr>

                    <tr>
                        <td>Total pending settlement</td>
                        <td>NGN {{ total_pending_settlement|intcomma }}</td>
                    </tr>
                </table>

            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->

        {% endblock %}